### PR TITLE
bugfix: scroll to top of modal, when modal is bigger than view

### LINKED ISSUE #1683: Can't scroll to the top of a modal
### Current Behavior

If the modal is taller than the screen a scrollbar appears but the top 20% of the modal is inaccessible. Issue for a modal with a long form and a phone.

Screenshot 2023-06-20 at 5 05 25 PM

### Expected Behavior

Being able to scroll to the top

### Steps To Reproduce

1. Create a tall modal
2. Reduce screen height (phone or dev tools)

### Link to Reproduction / Stackblitz

_No response_

### More Information

A PR adding the scrollbar on modals — the top was visible then [https://github.com/skeletonlabs/skeleton/pull/754](https://github.com/skeletonlabs/skeleton/pull/754)

### PR DESCRIPTION
**Pull request by Mahmoud-zino**
## Linked Issue

Closes #1683

## Description

Fixed the bug using the code [suggestion](https://github.com/skeletonlabs/skeleton/issues/1683#issuecomment-1599617938)

## Changsets

bugfix: fixed Scroll to the top of the modal, when the modal is bigger than the view.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
@Mahmoud-zino I think I mentioned this on Discord previously, but just so it's echoed here - I'd like to revisit the styling on this. I believe this is how we had the component styled previously and it introduced some issue for modals that were meant to fill the available screen space.

We may need to introduce a toggle or setting for this. I'll revisit asap.

**Comment by Mahmoud-zino** [comment]
@endigo9740 In the meantime I will do some testing 👍

**Comment by endigo9740** [comment]
@Mahmoud-zino I'm reverting this back to Draft until I can make my changes. This will likely occur next week after the next release.

**Comment by endigo9740** [comment]
@Mahmoud-zino after reviewing this again with a fresh set of eyes I think your changes will work for now. I do still have some concerns for edge cases, but for the majority of users this will likely work as desired. We'll monitor and if issues arise we'll revisit.

**Pull request merged**
