### PR TITLE
docs/filter-contributors-list

### LINKED ISSUE #2106: Filter GitHub sponsor users list on the homepage
### Link to the Page

https://www.skeleton.dev/

### Describe the Issue (screenshots encouraged!)

Looks like we have a couple users listed that should likely be filtered:

1. GitHub Actions (avatar with GitHub's icon)
2. Luke has two accounts (blue Tardis avatar), let's nix the one with the lesser contributions

Might also be nice to include more folks with smaller avatars - we have 90+ contributors, but only 50 are shown.

image

### PR DESCRIPTION
**Pull request by Mahmoud-zino**
## Linked Issue

Closes #2106

## Description

filter out mentioned contributors.
display up to 100 contributors.

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
FYI PR audits will be on Saturday or Sundays going forward, so expect a proper review then. I noted the old list is still displayed and the grid of icons is wrapping, so if that's something you want me to take a look at just let me know!

**Comment by endigo9740** [comment]
Ok, I see what you did here, you spliced the set into two groups. For some reason I thought both were the same people in my prior review. I think the vertical stack is really the only way to handle this many people, but I'm not sure I like emphasizing one group more than another so I've made everyone the same size.

Thanks for the help!

**Comment by Mahmoud-zino** [comment]
@endigo9740 Well, I didn't intend to diminish anyone's contribution 😄. However, you mentioned in the request that we might want to include the rest of the contributors with smaller sizes, so that's what I did 😄.

**Comment by endigo9740** [comment]
Not at all. Sometimes things are different when you see them implemented. I definitely think this is the way to go.

**Pull request merged**
