### PR TITLE
docs: Font Awesome cdn to npm

### LINKED ISSUE #2112: Update FontAwesome, replace Twitter with X in doc footer
### Link to the Page

_No response_

### Describe the Issue (screenshots encouraged!)

I don't like Twitter moving to "X", but sadly this seems to be a permanent change going forward. I'm seeing more companies move to the new branding, so we should likely follow their lead. This is the current iteration:

image

Let's drop the text label (because "X X" is silly) and go icon only like so:

image

Additionally, FontAwesome does include the new X logo:

https://fontawesome.com/icons/x-twitter?f=brands&s=solid

However, we use a local instance of FontAwesome, so this will likely need to be updated to use this. Let's go ahead and handle that alongside the above change. It might be worth considering moving to the NPM approach described here:

https://fontawesome.com/docs/web/setup/packages

### PR DESCRIPTION
**Pull request by Hugos68**
## Linked Issue

Closes #2112 

## Description

Removed CDN, added NPM package, removed brand texts, replaced twitter with x logo

Note: Because the text was removed from the brands the buttons are a bit small now, maybe it's a good idea to increase their size a bit.

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
@Hugos68 I had a small typo in my comment on the original thread. I meant to refer to the local assets in `/static`. Found here:

https://github.com/skeletonlabs/skeleton/tree/dev/sites/skeleton.dev/static

These are fairly hefty and will need to be purged as well. The NPM package will take over this.

**Comment by Hugos68** [comment]
Done.

**Comment by endigo9740** [comment]
@Hugos68 I modified the footer icons a bit. Just make them a bit easier to maintain with minimal markup. Other than that everything looks great. Thanks for handling this!

**Comment by Hugos68** [comment]
No worries, I do the same for all my projects, I have OCD patterns in code I need to follow or I go crazy.

**Pull request merged**
