### PR TITLE
Update examples for accordion autocollapse

### LINKED ISSUE #2240: Add accordion example without autocollapse
### Link to the Page

https://www.skeleton.dev/components/accordions

### Describe the Issue (screenshots encouraged!)

A recurrent question in our server it's if all `AccordionItem` can be closed, as the docs example uses `autocollapse`. As Chris suggested,  "We should probably update the example and docs to make this more clear. I'm thinking a toggle on the preview, plus a callout in the page"

### PR DESCRIPTION
**Pull request by phamduylong**
## Linked Issue

Closes #2240

## Description

Made Día de Muertos example non autocollapse and added a new auto collapse example

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by Sarenor** [comment]
Looking good! And since Autocollapse is a non-default option I think I'm fine with having it explained below the default, was thinking about wanting to have it up top.
Fine as it is for me though, after a bit of consideration.

**Comment by phamduylong** [comment]
Can this be merged then? I think it's fine for now, I have no rights to do the merging myself tho.

**Comment by Sarenor** [comment]
Me neither, that'll have to wait for Chris or someone else with merging rights.
I'm just here for an initial review.

**Comment by endigo9740** [comment]
@phamduylong We don't merge updates until they have been reviewed and unfortunately this is right in the middle of a busy couple weeks. My plan is to do a review this weekend as time allows.

With a quick glance this looks like it'll work, so I do expect it will be merged

**Comment by endigo9740** [comment]
@phamduylong this does exactly what we need here. Looks good. Thank for the contribution!

**Pull request merged**
