### PR TITLE
Add overflow-auto to modals to make them scrollable

### LINKED ISSUE #734: Modal is not scrollable
### Current Behavior

The modal is not completely viewable if the window height is smaller than the modal height. There is no scroll bar to view the entire modal.

### Steps To Reproduce

1. Create a tall modal
2. Open the web app on a smaller screen (or use the devtools mobile responsive viewer).

### Anything else?

https://www.skeleton.dev/utilities/modals

Example:
image

My modal has ten fields. I can't see the top fields or the submit button on a mobile device.

### PR DESCRIPTION
**Pull request by bennymi**
## Before submitting the PR:
- [X] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/skeletonlabs/skeleton/discussions) before submission.
- [X] Did you update and run tests before submission using `npm run test`?
- [X] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [ ] Did you update documentation related to your new feature or changes?

## What does your PR address?

Fixes #734. 

Added `overflow-auto` to the modal to make it scrollable.

### Tips
- Tap "convert to draft" to indicate this is work in progress.
- Link to an issue using the verbiage [Fixes #XX](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- Linked issues will auto-close when the PR is merged.

### CODE REVIEW

**Comment by bennymi** [comment]
@endigo9740 I think the best we can do is add a `mt-4` to the modal div, which would look like this:

image

But this then means that when the whole modal is visible it isn't fully centered anymore. Although the small difference isn't that noticable:

image

Using `my-4` on the modal div or `p-4` on the backdrop div doesn't work.

**Comment by endigo9740** [comment]
Gotcha, I figured that might be the case. Whatever works and looks good really.

Also side note - where is that drag handle coming from in the bottom-right corner. That's not native right? Do you have a browser plugin or something triggering that? First I've seen of that.

**Comment by bennymi** [comment]
@endigo9740 yeah that's actually from the browser 😄 Firefox and Chrome both have that feature where you can change the dimensions of the screen, that's when the drag handle shows up:

image

**Comment by endigo9740** [comment]
Ohhh I see. I didn't realize that's what you were using. I tend to opt for the fixed sizes in Chrome as oppose to the fluid option. I follow.

Btw, it's still not quite like I want. Do you mind if I jump in an take a quick swing at this? I'll push a small change in a moment if I can get it like I want it. (Sorry I'm so picky heh)

**Comment by bennymi** [comment]
@endigo9740 sure thing, give it a go! :)

**Comment by endigo9740** [comment]
Got it! Also fixed the trigger buttons being jacked up on mobile as well. I'll push this on sec...

Screen Shot 2022-12-30 at 4 32 56 PM

Screen Shot 2022-12-30 at 4 32 34 PM

**Comment by endigo9740** [comment]
I'm please with this, merging now!

**Comment by bennymi** [comment]
@endigo9740 nice! Looks much better than before!

**Pull request merged**
