### PR TITLE
Moved Prettier and ESLint to workspace root

### PR DESCRIPTION
**Pull request by eagerestwolf**
## Linked Issue

Addresses #2695 

## Description

This pull request is to address the desire for more consistent dev tooling. This is a partial implementation of the proposed fix outlined by @AdrianGonz97. Specifically, the following changes have been made:

- Added `.eslintrc.cjs` to repo root with a config that covers both React and Svelte, and has the possibility to support more frameworks in the future (i.e. Vue, Solid, etc.)
- Added `.prettierrc` to repo root with a config that supports Astro, Svelte, and Tailwind (React support is already included in Prettier)
- Added 2 plugin recommendations for VS Code (the official Microsoft ESLint extension and the official Prettier extension)
- Added an EditorConfig to the root of the workspace so contributors don't need to modify their editor settings.

Additionally, I made 1 stylistic choice. Prettier was setup with 4 space hard tabs, but most of the code seems to use 2 spaces, so I set Prettier to use 2 spaces for everything. Technically, I also made the choice of including `prettier-plugin-tailwindcss`, but that was already included in one of the packages.

I did run `pnpm ci:check`, but it's complaining about a missing component in the Svelte library, which I did not touch.

### What remains to be done?

I have ***NOT*** fixed the codebase yet. Since there are a few different coding styles present, both Prettier and ESLint have a lot of warnings and errors. I did not rectify these yet, however I am going to run `prettier -w` and `eslint`, then push those changes as a second commit (WARNING: that commit will touch *almost* every file in the repo because the code formatting is all over the place). I wanted to get an okay on the changes I have made before making any of those kinds of changes. Additionally, I did not readd the original GitHub workflow for checking linting and formatting, but that is easy enough to do later. Additionally, I did not standardize the scripts that are missing in the various projects as I feel I am not the best person to tackle those problems (except React, I added a `check` script that just does `tsc --noEmit`, which is perfectly fine for checking React code).

### What's next?

Ideally, I'd like to see this through to the end, to ensure that everything is done to the best of my abilities; but my ultimate purpose for being here is an audit and potential refactoring of the React components, which I hope to tackle as soon as I reasonably can. I am just very particular about coding standards, so this stuck out as a blocker for me.

## Changsets

Changesets aren't necessary. Changes were made to every package, but the changes made were all to dev tooling, not code.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`) (This change applies to the `next` branch, but I get the point)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [ ] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
Thanks @eagerestwolf I'll aim to review asap. Note you will need a changeset for this as you're touching a `/package` project

**Review by AdrianGonz97 — APPROVED** [review]
thanks for working on this!! 

I've gone ahead and resolved most of the errors, updated the workflows for CI, and tweaked some of the eslint and prettier settings so that they better match what we had before.

I also removed `sites/skeleton.dev` and `packages/plugin` since we don't need them anymore and they're presence is just clogging up lints and formatting logs.

Edit: 
Had to do one last commit since the Checks job was failing. This PR is good to go now 👍

**Comment by endigo9740** [comment]
Thanks for the help with this @AdrianGonz97

Just FYI guys, I'll probably go ahead and sit on this one until after the release tomorrow. That way we can test internally over the next couple weeks.

**Comment by eagerestwolf** [comment]
Good deal, I'll pull down the changes and start working on the refactor of some of the React components, just to help out on seeing how things are. I'll then stash my React changes once this gets merged and open a new PR for those. Over the coming week or so I'll also try to put together some React tips and guidelines for others.

**Comment by endigo9740** [comment]
@eagerestwolf I was able to coordinate with @AdrianGonz97 and @Hugos68 to audit the PR and make a few additional changes. First off, I appreciate the initiative, we're always need to have some help like this.

That said, there was a few things that we've adjusted this afternoon to preference. This includes:

## Disabled the Prettier Tailwind Plugin (for now)

I think it's a well intentioned change, but it doesn't mesh with how I write Tailwind classes. That's very much a *me* problem, but while I'm still authoring the lion share of the library, I'm going to request we hold off on this for now. But review it in the future. For now it's still installed as a dependency, but removed from the plugin list. We cannot revert the changes already made, so keep this in mind for the future. I'd appreciate opinionated changes are run by the team beforehand please ;)

Additionally, when we do re-enable it, we'll need to configure it to reach the style props found in the script blocks for each component. Right now it seems to only be affecting (some?) HTML templates. It's very hit or miss.

## Standardized Svelte/React Tests

There were some minor discrepancies between the commands used between Svelte and React packages, so we've now standardized those into a format that should scale regardless of the amount of test commands and/or frameworks added.

## Undone the Svelte @html rule

We made heavy use of this in Skeleton v2, but in v3 (or Svelte 5 in general) we're going to try to avoid this. It's a dangerous feature and not one to be used lightly. We have 2-3 locations this is still used for the docs and theme projects so we're instead using local ignore comments.

## VS Code Recommendations

Adrian made updates to attempt to auto-configure Prettier as the default formatter. Likewise, he added Svelte as a default recommended extension. We might extend this list over time, but this should be a great foundation.

## Tested the Commands

I ran through and tested all commands I could. Adrian did an amazing job with this. Most issues raised by the checks have been resolved, but if you could please take a look at the linting errors for the React > Ratings.tsx component please. Either as part of this PR or a follow up.

To run this, go to the root of the monorepo and run `pnpm lint`. You'll see three issues listed.

## Remaining Tasks

I'll return to this tomorrow to follow up on three things:

1. Any feedback you provide
2. Updated the Astro doc site > Contribution section to detail how to use these new commands
3. Updated our GitHub PR template checklist to encourage folks to run these commands

Aside from my, I anticipate being able to merge this by EOD tomorrow. Then I'll be out of office until Tuesday of next week. If you need any help between then, ping Adrian or Hugo on Discord please!

**Comment by eagerestwolf** [comment]
I have corrected the linting errors in the React ratings component, and the tests are still passing as well. As for the `prettier-plugin-tailwindcss` kerfuffle, I really had no ill intentions. Having your Tailwind classes sorted into a consistent order is great for compression as strings that have a lot of repeated words in a consistent order are easily compressed, and while I (and I'm sure you guys as well) have plenty of bandwidth, let's not forget that there are still large swaths of the US and Canada (not to mention the rest of the world) where dial-up or DSL are still the only option for internet. However, I forgot that TailwindCSS doesn't handle dynamic classes very well. That will (hopefully) be addressed with Tailwind V4 (assuming you switch to the Vite plugin). As for the Svelte rules, I really didn't touch those. I simply extended the `plugin:svelte/recommended` config. I seem to remember hearing that Rich made the `@html` rules a little stricter a while back due to the XSS risk, so that was probably just due to having a newer version of the svelte plugin. Sadly, I lack time right now to pour over the documentation, and I do have a large task ahead of me because there are quite a few things on the React side that will need to be addressed (including probably at least 1 or 2 component rewrites). It's not that anyone has done anything wrong, the current components just don't follow best practices, and a few have some very spaghetti code that could be pretty easily optimized. Again, nobody did anything wrong. You guys are just Svelte developers primarily, and given how different React is from Svelte, I'm impressed at what you've done on your own. I will also prepare a markdown doc of some of the React best practices (at least the important ones) over the weekend and try to get that into Discord and the Astro docs (well, that one will be in JSX, but you get the point) so that future contributions are always following the best practices. I shouldn't need anything in the meantime as it seems everything with the PR is pretty well sorted out on my end (other than the documentation, but I am limited on time since I work 60+ hours a week; I will get to it, I promise, you just have to be a little patient with me, as much as I would enjoy being a full time React dev, I lack the credentials to do that right now). My next contribution likely will be the documentation however as that is kind of important for future contributions, mainly relating to React; however, I'm sure a page on the docs about how to get VSCode fully setup for development within this repo would likely be much appreciated.

**Comment by eagerestwolf** [comment]
I also finally figured out the changesets and got that added. Changeset is obtuse. Turns out I had to run some complex git/bash magic to pull all the branch info from the origin.

**Comment by endigo9740** [comment]
Thanks for the help @eagerestwolf, and I appreciate you sorting out those React linting issues so quickly. Everything else was just "FYI", no action needed on your part.

I'll follow up on those final items listed in my post above and then we'll likely have this merged later today. This is a great improvement for the DX, so I'm exciting to see it in practice for future contributions!

As per contributions, everyone here is a volunteer, including myself. Feel free to help when you can or want to, but don't ever feel there's pressure to do so. We likely still have a couple months to go on the project, and any input on how we can improve the React experience will be helpful. Just the linting alone will help give us extra confidence going forward thoguh.

**Pull request merged**
