### PR TITLE
Exported current step from Stepper for easier dynamic styling and behaviour.

### PR DESCRIPTION
**Pull request by Sarenor**
## Before submitting the PR:
- [ ] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/skeletonlabs/skeleton/discussions) before submission.
- [x] Did you update and run tests before submission using `npm run test`?
- [x] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [x] Did you update documentation related to your new feature or changes? Updated automatically. Prop Discovery is awesome!

## What does your PR address?

Exports the current Step from the Stepper component so that conditional classes and other dynamic behaviour can be easily implemented without the user having to set up event listeners and make assumptions about the initial default state of the Stepper.

### CODE REVIEW

**Comment by endigo9740** [comment]
@Sarenor Hey, so the binded prop doesn't really meet my expectations as a user - I feel like I should be able to set the step value this way, not just see it update. How about we do the following instead:

- Revert the current changes
- Implement a new prop `start: number` that passes the desired starting step into the Stepper. It would have a default value of zero, and we would run `$state.current = start` on the component initialization
- Then we add a new dispatched event called `on:step`, which fires whether you're navigating forward or back. It would just a a combined version of `on:next` and `on:back`

This does a few things for us:
1. Makes it explicit how and where you set the initial step value
2. Keeps the `on:step` "actionable", meaning you not only get notified of the change through the event, but can use it as a function to trigger code when this occurs.

Thoughts?

**Comment by Sarenor** [comment]
Already agreed to the changes on Discord, let's see how well I code on just the laptop screen while in the train 😁

**Comment by Sarenor** [comment]
And that should do it. Went a bit explicit in the documentation, just tell me if you think it's to much and I'll remove it again :)

**Comment by endigo9740** [comment]
@Sarenor This is PERFECT, thank you sir! Merged!

**Pull request merged**
