### PR TITLE
fix: `setInitialClassState` function call

### LINKED ISSUE #1076: Issues with `setInitialClassState` in LightSwitch
### Current Behavior

In production builds, the lightswitch is pretty flaky. It seems to be caused by an issue with the following line: https://github.com/skeletonlabs/skeleton/blob/dev/src/lib/utilities/LightSwitch/LightSwitch.svelte#L65

The function string ends up minified, but the function call does not. Leading to this:
image

It also sometimes gets injected into the head twice, but I haven't been able to figure out a pattern there.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by knd775**
## Before submitting the PR:
- [X] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/skeletonlabs/skeleton/discussions) before submission.
- [ ] Did you update and run tests before submission using `npm run test`?
- [ ] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributing)? If not, please amend the branch name using `branch -m new-branch-name`
- [ ] Did you update documentation related to your new feature or changes?

## What does your PR address?
fixes #1076

### CODE REVIEW

**Comment by endigo9740** [comment]
Thanks @knd775, I seem to recall there was a reason we went with the string format we had prior. I'm going to bring in @AdrianGonz97 as a second set of eyes on this, as this was originally suggested by him.

**Comment by AdrianGonz97** [comment]
Ahh, yea that'll do it. Completely forgot how it'd be affected after minification. Turning it into an IIFE is the better solution so this looks good 👍

**Comment by endigo9740** [comment]
@knd775 Do you mind also updating the documentation on the Lightswitch page? It coincides with this:
https://skeleton-docs-git-fork-knd775-bugfix-light-0d93b4-skeleton-labs.vercel.app/utilities/lightswitches

Screenshot 2023-03-02 at 11 10 01 AM

Once that's done I'll aim to merge.

**Comment by knd775** [comment]
> @knd775 Do you mind also updating the documentation on the Lightswitch page?

Done!

**Pull request merged**
