### PR TITLE
Chore/update menu accessibility

### LINKED ISSUE #616: Improve accessibility functions of Menus
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It would be nice to also support up and down key events in menus and having click events toggle the menu open and closed (currently the menu only opens when the menu button is clicked, but it does not close it again on a second click).

According to this page https://www.w3.org/WAI/ARIA/apg/patterns/menu/ , Tabs and Shift+Tabs should also close the menu.

I could work on this as well.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

[Headless UI](https://headlessui.com/react/menu) has a nice example.

### PR DESCRIPTION
**Pull request by bennymi**
## Before submitting the PR:
- [X] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/skeletonlabs/skeleton/discussions) before submission.
- [X] Did you update and run tests before submission using `npm run test`?
- [X] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [x] Did you update documentation related to your new feature or changes?

## What does your PR address?

Improves menu accessibility by including up and down arrow key functionality and being able to open and close the menu by clicking the menu button. This Resolves #616. 

When the menu is opened, using the arrow down key starts at the top and allows the user the move to the next menu items downwards.

When the menu is opened with a click and the arrow up key is used, the last menu item gets focused first. 

### Tips
- Tap "convert to draft" to indicate this is work in progress.
- Link to an issue using the verbiage [Fixes #XX](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- Linked issues will auto-close when the PR is merged.

### CODE REVIEW

**Comment by endigo9740** [comment]
Awesome thanks @bennymi. It's Saturday for me which is my off day, but I'll give this a proper review tomorrow. Excited to try it out!

**Comment by bennymi** [comment]
Hey, no worries Chris. Enjoy your day off!

**Comment by endigo9740** [comment]
@bennymi Hey, maybe I'm doing something wrong here, but I can't seem to get this to work. From my understanding when a menu is open I should be able to use the up/down arrows to navigate up/down the list of focusable elements within the menu. Is this correct?

Currently we have a couple menus in the documentation that should support this. The "Features" drop down menu at the top of the page, in the App Bar. Plus the Navigation demo on the Menu docs page. Neither behave in this manner when tested though. The page just scrolls slightly up and down. A couple considerations:

* I assumed it was a small bug that focus was not set correctly when the menu opens, but no, even manually adjusting focus I can't seem to get this to work.
* It looks like you're only setting the list of focusable elements during init. However, you might make considerations to update this list each time the menu opens. What if the contents of the menu are reactive and change between viewing? Then your original list if focusable elements is outdated.
* Additionally, if you are introducing keyboard interaction, make sure to update the documentation accordingly. No one will know about this feature if we don't tell them it's enabled.

Screen Shot 2022-12-05 at 10 41 12 AM

For now I'll drop this PR into a draft state. Tap the "ready for review" action on this page when adjustments have been made and this is ready for another review pass.

**Comment by bennymi** [comment]
@endigo9740 thank you for the feedback. I updated the documentation and made sure that up and down arrow keys no longer cause scrolling when a menu is open. But I'm still stuck on one problem. The up and down arrow keys do work when clicking on a menu in both Firefox and Chrome in my testing, but the focused element is only highlighted in Firefox, not in Chrome. 

This only happens when a click is used to open the menu. When <kbd>Enter</kbd> is used to open a menu after it was focused, then the menu items are also highlighted in Chrome.

Firefox after clicking on a menu and using the arrow up key:
image

Chrome after clicking on a menu and using the arrow up key:
image

Do you have an idea what could be the reason here?

**Comment by endigo9740** [comment]
@bennymi Interesting, so I'll need to review our focus styling for these soon. That's odd because tab focus workings fine in Chrome. Ok I'm going to mark this ready for review and do another pass with this info tomorrow. Thanks!

**Comment by bennymi** [comment]
@endigo9740 yes it's strange behavior, because when I tab to a menu button and hit enter and the arrow up key I do get focus styling in Chrome as well:

image

It just doesn't work when the menu is clicked and then the arrows are used.

**Pull request merged**
