### PR TITLE
Added JSDoc comments to outputted d.ts files

### PR DESCRIPTION
**Pull request by niktek**
Updated post build script to add JSDoc blocks from svelte components into the emitted .d.ts files.

### CODE REVIEW

**Comment by endigo9740** [comment]
Calling for help from all available testers! We're wanting to test this in real applications to ensure things are working as expected. If you're willing and able, please follow the instructions below:

1. Download and install the Tarball file linked below. [Install instructions here](https://github.com/skeletonlabs/skeleton/wiki/Create-and-Install-Test-Packages).
2. Either setup a new project and add various components, or use an existing project
2. Hover over component props, slots, events, etc that use [JSDoc comments](https://www.skeleton.dev/docs/contributions/documentation)
3. Ensure the descriptions and info over hover is accurate and relevant.
4. Report any issues found in this PR thread please!

> NOTE: this is NOT for production use, but local testing within production apps is very much welcome!

[skeleton-jsdocs-test.zip](https://github.com/skeletonlabs/skeleton/files/10389081/skeleton-jsdocs-test.zip)

**Comment by niktek** [comment]
Quick clarification - this is props only, Intellisense doesn't seem to list any events/slots (even without descriptions).

**Comment by endigo9740** [comment]
New PR here, which covers Props + Events: https://github.com/skeletonlabs/skeleton/pull/826

**Comment by Sarenor** [comment]
As said in Discord, successfully tested this with my wiki app. I am in love.

**Comment by endigo9740** [comment]
Thanks @Sarenor

**Pull request closed without merging**
