### PR TITLE
Docs/tailwind blocks image layout page

### LINKED ISSUE #1600: Tailwind Blocks - Image Layouts
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I'd welcome a contribution for a new Tailwind > Blocks > Image Layouts page that demonstrates how to handle image grid or masonry layouts. This can draw straight from what Flowbite provides (with attribution) except the images used. Those are owned and hosted by Flowbite. We would of course want to exchange those for new images - like from Unsplash, ex:

```
// Format as: https://source.unsplash.com/{imageID}/{dimensions}
https://source.unsplash.com/YOErFW8AfkI/128x128
```

Ideally these would keep the Día de los Muertos theme going.

To show how well this works, here's a couple examples of copying Flowbite's markup directly to our project examples:

Screenshot 2023-05-29 at 3 31 44 PM

Screenshot 2023-05-29 at 3 32 04 PM

### What type of pull request would this be?

Docs

### Provide relevant links or additional information.

- https://flowbite.com/docs/components/gallery/#default-gallery
- https://flowbite.com/docs/components/gallery/#default-gallery

### PR DESCRIPTION
**Pull request by FarhanAliRaza**
## Linked Issue

Closes #1600 

## Description

Added a page in documentation for images layout

## Changsets

Changesets automate our changelog. If you modify files in `/package/skeleton`, run `pnpm changeset`, follow the prompts, then commit the markdown file. Changes that add features should be minor while chores and bugfixes should be patch. Please prefix the changeset message with `feat:, bugfix: or chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing/style-guide#feature-branches).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Includes a changeset (if relevant; see above)
- [x] Ensure code linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`

### CODE REVIEW

**Comment by endigo9740** [comment]
Thank you @FarhanAliRaza, so a few bits of feedback:

1. The checklist in the PR message above actually creates interactive checkboxes. No need to insert emoji there. I've corrected this for you.
2. We typically don't create Changesets for pure documentation updates, but the Changeset is responsible for generating our changelog. I'd really like for this change to be mentioned there, so please follow the Changeset instructions provided in the message above as well. Prefix with `feat:` and this will be considered a `minor` update.
3. Per the contribution itself, the page looks great, but go ahead and remove the "Default Gallery" section with the code snippet. That's redundant with the code blog provided by the featured example at the top of the page.
4. Go ahead and bump up the dimensions of the featured example at the top to `300x300`. This should ensure it fills the full width for larger displays.
5. The masonry example is only showing 2 columns for me - is there any way we can match the 4 column layout of the Flowbite reference? If you need help picking or sizing additional images let me know. Glad to help!
6. Likewise only the featured demo at the top should keep the gradient background - set the Masonry DocPreviewer component to have a prop of `background="neutral"` please
7. The "Featured Image" section is cool, but doesn't quite size correctly on larger screens, and for this to work properly we would need to introduce some JS logic. Let's go ahead and leave that one, but comment it out for now. I'll circle back to that in the near future.
8. One of the issues with Flowbite's source is they have `alt` tags but do not populate them. Do you mind either removing the alt tags or populating them please?
9. Finally, as mentioned in the original post, we're borrowing this directly from Flowbite. Even though Flowbite is covered under an MIT license and open source, let's provide the courtesy of attribution here. [Here's an example](https://www.skeleton.dev/utilities/local-storage-stores#attribution) for how to handle that. I'll provide text below.

Per Attribution, add the following:
> Image layout markup and styles provided courtesy [Flowbite](https://flowbite.com/). Please [view our guide](https://www.skeleton.dev/blog/skeleton-plus-flowbite) to integrating even more Flowbite elements into your project.

**Comment by endigo9740** [comment]
Hey @FarhanAliRaza I see you've pushed revisions based on my feedback. Thank, this looks absolutely beautiful. Again, brilliant choices of images.

That said, we're going to be need to hold back this PR being merged for a short while, for two reasons:

1. It seems some `package-lock` changes made it into your commit. We're going to reviewing our end the best way to handle this, as this could be detrimental if merged as is. No fault on you, we've just started using `pnpm` recently and this a new issue for us to address.
2. I'm actually planning to meet with Zoltan, the creator of Flowbite, late next week. I'd actually like to show this to him directly and give his approval before we merge and go public with it.

Just wanted to give you a heads up - we do plan to move forward with merging this, and I'll keep you posted when this occurs. Unfortunately it won't make it in by next week's release, but I'd expect it to be in place by the following.

Thank you for contribution! I'm super excited to share this!

**Comment by endigo9740** [comment]
@FarhanAliRaza two quick follow ups that we'll need fixed:

1. Make sure the page title and URL are "Image Layouts" (plural) to follow our doc conventions
2. Looks like `Masonry` was missed on the doc page as `Masonary`

If we come across anything else we'll let you know. But no rush per the comment above.

**Comment by endigo9740** [comment]
@FarhanAliRaza We got the thumbs up from Zoltan and I've implemented a couple minor tweaks, so merging this now. Thanks again for your contribution. This will be included as part of the next release of Skeleton.

**Comment by FarhanAliRaza** [comment]
[Hover Card - shadcn_ui - Awesome Screenshot.webm](https://github.com/skeletonlabs/skeleton/assets/62690310/dac8ad31-9576-4d58-a337-1356b63e7a6c)
not related but I have a question. when we use hover in the popup the popup menu closes when we move away from the button. But it will be greater if we hover on the popup body it should not disappear.  like shown in the video. Should i open a issue? I want to contribute

**Comment by endigo9740** [comment]
@FarhanAliRaza I'd recommend you look at our roadmap to understand our future plans regarding popups:
https://github.com/skeletonlabs/skeleton/discussions/1367

In short, these will be split off, rebuilt to more tightly couple Floating UI, and the feature set improved and expanded. We hear the desire for features like this all the time, we're aware of them, but do have some technical prerequisites in play before we can begin implementing these changes.

**Pull request merged**
