### PR TITLE
feat: add generic parameters to Modal interfaces

### PR DESCRIPTION
**Pull request by matadaniel**
## Description

Improve Modal types

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [ ] This PR targets the `dev` branch (NEVER `master`)
- [ ] Documentation reflects all relevant changes
- [ ] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [ ] Ensure Svelte and Typescript linting is current - run `pnpm check`
- [ ] Ensure Prettier linting is current - run `pnpm format`
- [ ] All test cases are passing - run `pnpm test`
- [ ] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
@AdrianGonz97 @ryceg if you guys get a chance you can please review this one. Thank you!

**Comment by ryceg** [comment]
Yeah this looks solid- I'll give it a spin but it's quite a minimal change, but will allow for much better DX.

**Comment by matadaniel** [comment]
I made it a draft PR since you said it would allow you to review sooner rather than later, and I wanted a review to make sure no one's current types would break. I have also not completed much of the PR template checklist.

I did come across a discussion that I am unable to find now that mentioned that the ModalSettings.value type should stay as any rather than string. I will add it to the ModalSettings' generic parameters.

**Comment by endigo9740** [comment]
@matadaniel I've had a chance to do a quick review. Overall things look to be working as expected. No regressions have been found per my tests.

Though note you do seem to be missing a Changeset. If you could please follow the instructions provided in the original post at the top of this thread please. Aside from that, I'd recommend either catching your branch up to `dev` or skipping `pnpm format` from our checklist - it's reporting issues that I believe have already been resolved.

I'm going to once again ping @ryceg and @AdrianGonz97 to double check that the most recent type changes are sound. If you guys could please use the GitHub PR approval system to report your response please!

I'll plan to merge once:

- The changeset is added
- The checklist above is completed
- Rhys and/or Adrian submit their approval

Thanks!

**Comment by endigo9740** [comment]
@matadaniel given this PR is getting a bit long in the tooth I'm going to suggest we finalize things by end of this week. Otherwise I'll just make the assumption this isn't moving forward and close the PR.

@Hugos68 I'm going to add you as another reviewer since you have a strong handling of types.

To all - If I can get one of the three folks tagged here to help confirm, this will be merged per the conditions listed in my post above.

**Comment by endigo9740** [comment]
Alright, we've reached end of the week with no activity so I'm going to call this abandoned and close this out. Just FYI, we're in the midst of shifting our focus from Skeleton v2 -> v3, so this was the last pending item we had hanging on. This now enables us to move forward.

Given I do think there's some valuable change here, I've referenced this PR for consideration when we implement the new overlay system in Skeleton v3 here. So some version of this may come back in the future:
https://github.com/skeletonlabs/skeleton/issues/2357

**Pull request closed without merging**
