### PR TITLE
Next - Theme Generator

### PR DESCRIPTION
**Pull request by endigo9740**
## Linked Issue

https://github.com/skeletonlabs/skeleton/issues/1142

## Description

Scaffolds the new SvelteKit-based theme generator website.

- `/sites/themes.skeleton.dev`

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [ ] This PR targets the `dev` branch (NEVER `master`)
- [ ] Documentation reflects all relevant changes
- [ ] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [ ] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [ ] Ensure Prettier linting is current - run `pnpm format`
- [ ] All test cases are passing - run `pnpm test`
- [ ] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
@ryceg FYI, this will be the new theme generator app!

**Comment by endigo9740** [comment]
@nick3842 will you help take a look at why this is:

1. Being picked up by the Vercel CI/CD process (maybe because it defaults to target `dev` branch?)
2. Why it's failing - which may be a non-issue once it's picked up on Cloudflare

If we can get this in a working state, then I think this PR is ready to merge. The app doesn't do much, but it stubs out it's position in the monorepo, and should allow us to close: https://github.com/skeletonlabs/skeleton/issues/2352

**Comment by endigo9740** [comment]
@ryceg I've requested a review from you. The plan is to merge accept feedback over the next 24 hours from you and any other team members. I'll plan to implement that tomorrow, then current progress will be merged into the Next branch. This will then unblock us to move forward on other initiatives, including:

* Implementing our Lightswitch solution for light/dark mode across ALL apps
* Implementing a theme switcher in at least the documentation site
* Audit and balance color selection for many default Tailwind plugin provided utility classes

These additions will help contributors currently working to build the components be able to quickly preview in both light/dark mode and preview with a number of themes applied.

This does not signal this feature is in anyway complete. Merely that it's ~good enough~ to progress to the next step of things. I'd still love your help in improving the typing, color balance, accessibility features, etc. All of those can be handled in either dedicated PR passes.

If you don't have time to review right now, that's fine. But the door is open for these additional updates at any time.

**Comment by TazorDE** [comment]
image
Not sure if it's a Windows issue, but the select options appear not to be colored correctly when in dark-mode. Light-mode does work

**Comment by endigo9740** [comment]
Bug: when seeing a value you can pass any valid color CSS value, ex `red`. But the seed function is not parsing this to a hex when inserted into the state.

**Comment by niktek** [comment]
Might be worth updating to modern font stacks to expand the font selection before worrying about any external font referencing.

```
theme: {
    fontFamily: { // https://github.com/system-fonts/modern-font-stacks
      systemui:     ['system-ui', 'sans-serif'],
      transitional: ['Charter', 'Bitstream Charter', 'Sitka Text', 'Cambria', 'serif'],
      oldstyle:     ['Iowan Old Style', 'Palatino Linotype', 'URW Palladio L', 'P052', 'serif'],
      humanist:     ['Seravek', 'Gill Sans Nova', 'Ubuntu', 'Calibri', 'DejaVu Sans', 'source-sans-pro', 'sans-serif'],
      geohumanist:  ['Avenir', 'Montserrat', 'Corbel', 'URW Gothic', 'source-sans-pro', 'sans-serif'],
      classhuman:   ['Optima', 'Candara', 'Noto Sans', 'source-sans-pro', 'sans-serif'],
      neogrote:     ['Inter', 'Roboto', 'Helvetica Neue', 'Arial Nova', 'Nimbus Sans', 'Arial', 'sans-serif'],
      monoslab:     ['Nimbus Mono PS', 'Courier New', 'monospace'],
      monocode:     ['ui-monospace', 'Cascadia Code', 'Source Code Pro', 'Menlo', 'Consolas', 'DejaVu Sans Mono', 'monospace'],
      industrial:   ['Bahnschrift', 'DIN Alternate', 'Franklin Gothic Medium', 'Nimbus Sans Narrow', 'sans-serif-condensed', 'sans-serif'],
      roundsans:    ['ui-rounded', 'Hiragino Maru Gothic ProN', 'Quicksand', 'Comfortaa', 'Manjari', 'Arial Rounded MT', 'Arial Rounded MT Bold', 'Calibri', 'source-sans-pro', 'sans-serif'],
      slabserif:    ['Rockwell', 'Rockwell Nova', 'Roboto Slab', 'DejaVu Serif', 'Sitka Small', 'serif'],
      antique:      ['Superclarendon', 'Bookman Old Style', 'URW Bookman', 'URW Bookman L', 'Georgia Pro', 'Georgia', 'serif'],
      didone:       ['Didot', 'Bodoni MT', 'Noto Serif Display', 'URW Palladio L', 'P052', 'Sylfaen', 'serif'],
      handwritten:  ['Segoe Print', 'Bradley Hand', 'Chilanka', 'TSCu_Comic', 'casual', 'cursive'],
    },
    ```
    
From https://modernfontstacks.com/ courtesy of https://www.youtube.com/watch?v=VOd6jfAImV4

**Comment by Sarenor** [comment]
The App handles beautifully. I'm missing one well loved feature from the previous iteration though (or I just missed it):
The randomize all button so you can rapid fire try multiple color combinations.

It's not particularly _useful_ so I could understand not bringing it back, but it's always been fun.

**Review by Sarenor — APPROVED** [review]

**Comment by endigo9740** [comment]
@niktek that's beautiful, exactly what I was looking for as a stopgap until more custom font settings are possible.

@Sarenor drop that comment over in the issue thread - we'll circle back to it in the next pass. It should very much be possible, along with the potential for randomizing OTHER sections, or maybe even ALL settings.

**Pull request merged**
