### PR TITLE
feat: export initialize stores for Modal, Toast and Drawer

### PR DESCRIPTION
**Pull request by ibilux**
## Linked Issue

Closes #{issueNumber}

## Description

Export initialize stores for Modal, Toast and Drawer

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
@ibilux I reviewed this with @AdrianGonz97 yesterday, who implemented the change to the stores for these features. He confirmed the choice was deliberate not to export the initialize methods. Though I don't know the specifics - perhaps he can elaborate.

Can you maybe explain your goals here? Are you encountering a specific issue that you believe this would help with?

**Comment by AdrianGonz97** [comment]
As @endigo9740 mentioned, these functions were purposefully not exposed to simplify the surface area of the API. Rather than having to initialize each store individually, they can all be initialized with `initializeStores`. If you're concerned about the "overhead" of initializing all of them, I wouldn't worry about them since it's extremely minimal.

**Comment by ibilux** [comment]
@endigo9740 If I don't want to use a store for some case it shouldn't be initial. I want to control what stores to initialize.

**Comment by ibilux** [comment]
@AdrianGonz97 I want to control what stores to initialize and use, in case I want to implement different store or extend one of them.

**Comment by AdrianGonz97** [comment]
@ibilux 
Sure, I can understand wanting more control over that. But how does exporting the individual store initializers help you achieve "implement different store or extend one of them"? 

If anything, it would make more sense to expose their respective services that generates the stores so that you can set them yourself... 

Additionally, if you really want to extend our stores, you're free to get them from context and modify them from there.

**Comment by endigo9740** [comment]
@ibilux I might suggest we go ahead and close this out. I don't think this something we're going to move forward with. I'd suggest following Adrian's advice above instead.

If you you would like to open a GitHub Discussions thread to discuss further or need additional support, please feel free to tag either of us. Otherwise we're available on Discord in the `#contributors` channel most weekdays.

**Pull request closed without merging**
