### PR TITLE
Bugfix/recursivetreeview issue after changing nodes

### PR DESCRIPTION
**Pull request by KaiStarkk**
# Draft

## Description

This adds tests for a bug identified in #2875 . This adds 4 new tests for RecursiveTreeView which isolates the issue to one specific test, the other 3 pass.

I've submitted this PR as draft since the tests are useful, but this isn't yet a fix. Will work on it shortly.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
  _^ This caused an unrelated edit which has been added as a separate commit_
- [ ] All test cases are passing - run `pnpm test`
  _^ There were already failing tests on dev_
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by KaiStarkk** [comment]
Just a note regarding the package upgrades, only the upgrades to testing packages were strictly necessary (vite-plugin-svelte and jest-dom) to get tests working properly, but I've aimed to resolve all updates to this point in time.

**Comment by endigo9740** [comment]
Than you @KaiStarkk, please make sure to mark the PR "ready for review" when it reaches that state. We'll review and aim to provide feedback and/or merge asap.

**Comment by endigo9740** [comment]
@KaiStarkk another quick reminder this is awaiting your final changes and the status being bumped up to "ready for review". Please let me know if this is continuing forward, otherwise I'll assume this is abandoned and remove. Please and thanks!

**Comment by KaiStarkk** [comment]
Hi @endigo9740 , I had another look on the weekend but wasn't able to figure out the problem. Assuming the tests are still valuable, should I switch this to ready and rename it as adding the tests, rather than a fix?

I will have another go at it this weekend too

**Comment by endigo9740** [comment]
Sounds good @KaiStarkk, I'll check back next week if I don't hear from you sooner then.

**Comment by endigo9740** [comment]
@KaiStarkk I would think if the tests are failing then this is not in a functional state. Unfortunately I am just completely absorbed in our v3 progress right now, so I can't really pause to help at the moment. But I'll bring this up with the team and see if they have any other ideas.

**Comment by KaiStarkk** [comment]
These tests are still valid but anyone searching can cherry pick if needed. Closing as Svelte 5 is out now, I see that it makes much more sense to look into Skeleton 3

**Pull request closed without merging**
