### PR TITLE
Docs Audit - Utilities

### LINKED ISSUE #1049: Audit and Improve Doc Content
Per: https://github.com/skeletonlabs/skeleton/issues/783

The goal of this ticket will be to divvy up ownership of several sections of the documentation. Each volunteer will be assigned an allotment of pages that they will own. You should audit, review, and either submit feedback - or better yet send a PR with fixes and adjustments in place.

## How to Participate

> **Warning** please DO NOT volunteer if you cannot have your changes completed by Sunday March 5th.

1. Reach out in the `#docs-overhaul` channel on [Discord](https://discord.gg/EXqV7W8MtY) to volunteer
    - Post your GitHub username (I'll assign you below)
    - Let us know which section you wish to be assigned
2. Immediately create a draft PR (pull request), including your checklist as shown below ([reference](https://www.skeleton.dev/docs/contributing))
    - Important: You will not be considered assigned until a draft PR is available
4. As you complete changes per page, commit it, then tick the box in the PR to alert everyone of your progress
5. Set your PR to "ready for review" when all sections are complete
6. Finalize all changes by Sunday March 5!

### Can't submit a PR?

View the dev branch docs here:
https://dev.skeleton.dev/docs/introduction

You can still help by locating issues for other volunteers, reviewing the blog posts, or helping with PR reviews. When submitting feedback, tag the assigned user, or consider keeping feedback feedback localized in each PR thread. Use a checklist so we can tick off items as completed!

## Responsibilities 

> Try to follow any obvious existing conventions. Contact a contributor on Discord for additional questions!

- Scan the page for typos, grammar, etc (including each tab)
- Check the page for broken links
- Keep headings short, consistent, and semantic to the section (no wrapping in Table of Contents)
- Keep paragraph text short, concise, and descriptive - ideally 1-2 lines max
- Use `h2` for main headers, `h3` for subheaders
- Use `<section class="space-y-4">...</section>` to divide page sections
- `prop`, `slots` and `event` tab data is auto-documented via inline JSDocs comments ([reference](https://www.skeleton.dev/docs/contributing/documentation))
- Ensure auto-documented tables aren't missing props (it happens!) and descriptions are semantic
- The `classes`, `params`, and `keyboard` tabs are manually maintained, which means more room for error
- Avoid inserting Font Awesome icons in code snippets - Skeleton is icon library agnostic!
- On CodeBlock snippets remove trailing indents so that they are not copied over to the clipboard

> See the [Doc Updates](https://github.com/skeletonlabs/skeleton/issues/783) comments for suggestions made by other users.

## Standby Volunteers

Folks that aren't committing to any section, but are available to help scan for issues or check other's work:

- @riziles
- @SebasF1349 
- @dirk-bester
- (Hugos)

## Source

- `/src/lib/{category}/{feature}` - the library features themselves (components, element styles, etc)
- `/src/routes/{category}/{feature}` - the documentation pages for each respective feature

### Blog (open/anyone)

> **Note** - review each blog post. Scan for out of data info, typos, etc. Report issues in the comments below.

### Tailwind - Group 1 ([oatnog](https://github.com/oatnog))

PR: (not yet available)

- [ ] Core
- [ ] Typography
- [ ] Forms
- [ ] Alerts
- [ ] Badges

### Tailwind - Group 2 ([DukeRupert](https://github.com/DukeRupert))

PR: (not yet available)

- [x] Breadcrumbs
- [x] Buttons
- [x] Cards
- [x] Chips
- [x] Lists
- [x] Logo Clouds
- [x] Placeholders
- [x] Tables
- [x] Gradient Headings

### Svelte - Group 1 ([niktek](https://github.com/niktek))

PR: [1054](https://github.com/skeletonlabs/skeleton/pull/1054)

- [x] Clipboard
- [x] Filters
- [x] Focus Trap
- [x] Accordions
- [x] App Bar
- [x] App Rail
- [x] App Shell
- [x] Avatars
- [x] Conic Gradients
- [x] File Buttons
- [x] File Dropzone
- [x] Input Chips

### Svelte - Group 2 ([RyanTheGuy](https://github.com/RyanTheGuy))

PR: https://github.com/skeletonlabs/skeleton/pull/1055 (ready for review!)

- [x] Listboxes
- [x] Paginators
- [x] Progress Bars
- [x] Progress Radials
- [x] Radio Groups
- [x] Range Sliders
- [x] Slide Toggles
- [x] Steppers
- [x] Tabs
- [x] Tables
- [x] Table of Contents

### Utilities ([DukeRupert](https://github.com/DukeRupert))

PR: https://github.com/skeletonlabs/skeleton/pull/1071

- [x] Code Blocks
- [x] Drawers
- [x] Lightswitch
- [x] Local Storage Store
- [x] Modals
- [x] Toasts
- [x] Popups

### Docs Sections - Group 1 (@Sarenor)

PR: https://github.com/skeletonlabs/skeleton/pull/1084

- [x] Docs > Introduction
- [x] Docs > Get Started
- [x] Docs > Colors
- [x] Docs > Styling
- [x] Docs > Design Tokens
- [x] Docs > Variants
- [x] Docs > Theme generator
- [x] Docs > Quickstart

### Docs Sections - Group 2 (@Sarenor)

PR: https://github.com/skeletonlabs/skeleton/pull/1086

- [x] Docs > Contributing > Requirements
- [x] Docs > Contributing > Style Guide
- [x] Docs > Contributing > Documentation Guide
- [x] Routes > Templates > +page.svelte
- [x] README
- [x] Page footer

### Homepage

- See: https://github.com/skeletonlabs/skeleton/issues/1070

### PR DESCRIPTION
**Pull request by DukeRupert**
Resolves #1049 

## Utilities
- [x]  Code Blocks
- [x] Drawers
- [x] Lightswitch
- [x] Local Storage Store
- [x] Modals
- [x] Toasts
- [x] Popups

### CODE REVIEW

**Comment by endigo9740** [comment]
@DukeRupert looks like there was a bit of a miscommunication, so heads up about some changes made in this PR:
https://github.com/skeletonlabs/skeleton/pull/1073

**Comment by dirk-bester** [comment]
Ok, that is my bad, I was looking at old stuff that showed the section as unassigned still. Single file though so it should not be horrific.

**Comment by Sarenor** [comment]
Small one, but the current setter imports reference (I assume) old function imports.

import { setUserPrefers, setMode } from '@skeletonlabs/skeleton';
should be

import { setModeUserPrefers, setModeCurrent } from '@skeletonlabs/skeleton';

**Comment by DukeRupert** [comment]
@dirk-bester No problem, we are moving fast which means that this is kind of inevitable. Thanks for helping. @endigo9740 Thanks for giving me the heads up.

**Comment by DukeRupert** [comment]
@endigo9740 On the lightswitch page the title does not match the url, which is different from the others. Would you like it to be singular, plural or keep it as is?

lightswitch

**Comment by endigo9740** [comment]
@DukeRupert let's go ahead and leave that as is. Our convention for URLs is plurals, but the singular version reads better on the page itself. We reference that page from a couple places in the docs, so easiest solution is just to leave it. But thanks for asking!

**Comment by dirk-bester** [comment]
https://skeleton-docs-p4sbl8cv7-skeleton-labs.vercel.app/utilities/drawers abitrary strikes again. Could probably use a global search for it. I see 20 locally but I am not merged to the latest atm.

**Comment by dirk-bester** [comment]
https://skeleton-docs-p4sbl8cv7-skeleton-labs.vercel.app/utilities/drawers
Props, the bottom 2

labelledby | string | - | Provide an ID of the element labeling the drawer.
-- | -- | -- | --
describedby | string | - | Provide an ID of the element describing the drawer.

Everything is camelCase except these two.

**Comment by dirk-bester** [comment]
https://skeleton-docs-p4sbl8cv7-skeleton-labs.vercel.app/utilities/local-storage-stores

const storeExample: Writable<string> = localStorageStore('storeExample', 'initialValueHere');
This self documents via 'initialValueHere'

// Subscribe to the store
storeExample.subscribe(() => {});

Should this and similar do something like a console log? Or 'typical' usage?
Or maybe in a future "examples" effort link to source code in example apps?

Anything to make it a quick concise learn rather than yet another research project when you are brand new to svelte and skeleton and typescript and everything. Speaking from recent and continuing experience of course ;-)

**Comment by dirk-bester** [comment]
https://skeleton-docs-p4sbl8cv7-skeleton-labs.vercel.app/utilities/modals

.w-modal | - | Sets a standard responsive width for modals.
.w-modal-slim | - | Create a slimmer modal. Great for small component modals.
.w-modal-wide | - | Create a wider modal. Great for full screen component modals.

It is unclear to me where I would use these classes.

**Comment by endigo9740** [comment]
@dirk-bester Good feedback. To address each post above:

- We're aiming to do global fixes last, rather than in these piecemeal passes. We will fix the arbitrary spelling soon.
- label/describeby are ARIA attributes. They are verbatim here. We'll leave those as is
- All instruction for local storage store comes from the original author (see the link at the bottom of the page). Again I suggest we leave as is unless people starting raising and issue - you're the first in the months since this was added.
- I agree with the modal classes. These are demonstrated in the example component modals, but a small bit of text in the accordion would be beneficial. They're for standardizing custom modal width sizes.

**Comment by endigo9740** [comment]
@DukeRupert I'm devoting some time to these PRs today, so I'll go ahead and implementing the remaining items per my message above. Then aim to merge this in to dev branch. Thanks again for your contributions!

**Pull request merged**
