### PR TITLE
docs/Add new Integrations section + Tauri guide

### PR DESCRIPTION
**Pull request by SebasF1349**
## Description

Added new integrations section and a guide to integrate Skeleton with Tauri.

This is mostly done, but I still want to add a template for people to use so it's not ready to merge. As it's not complete, changeset hasn't been added yet.

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages/skeleton`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [ ] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by niktek** [comment]
Just a suggestion, but maybe to show the logical flow a bit more clearly, have the headers like:

- Create your Skeleton project
- Modify your Skeleton project for Tauri
- Add the Tauri backend

I can see people sort of clicking on the https://tauri.app/v1/guides/getting-started/setup/sveltekit#sveltekit-in-ssg-mode and doing a top down follow of those instructions and having a pure SK and a separate Skeleton install

**Comment by endigo9740** [comment]
@SebasF1349 I've created the repo for the source project:

https://github.com/skeletonlabs/skeleton-starter-tauri

I've invited you to join this with admin-level access so you have full control. It's set public now. Change whatever you need or what.

**Comment by SebasF1349** [comment]
Thanks for your suggestion. I have taken them all into account for this new version. The repo is missing as I still need to add an example on how to communicate the frontend with the backend.

**Comment by endigo9740** [comment]
@SebasF1349 I've pushed my changes. I tried to preserve the overall structure and instruction, while making updates to the text and styling. In most cases I tried to narrow this down to only the most critical information. This tends to lead to the most success when it comes to teaching. There's likely a few typos, but let me know if this works. And of course, please verify that all instructions remain accurate!

Overall great job with this, it's brilliant. I can't wait to see what folks build with it!

**Comment by Sarenor** [comment]
@SebasF1349 
Sorry, block of feedback incoming:

- The Video Guide and the manual installation blocks are completely separately from each other, aren't they? We might want to better communicate that with something like "you can either follow this video and then our manual instructions or you can follow the completely manual steps outlined below"

- Open your root layout, found in /src/routes/+layout.svelte, then append the following two lines at the top of the script tag. This will disable both server-side rendering (SSR) and prerendering).
```js
export const prerender = true
export const ssr = false
```
Does ``prerender = true`` really disable prerendering?

Otherwise it's looking excellent and I like it!

**Pull request merged**
