### PR TITLE
Update installation instructions

### LINKED ISSUE #2653: Finalize v3 installation instructions for all meta-frameworks
### Link to the Page

https://next.skeleton.dev/docs/get-started/installation

### Describe the Issue (screenshots encouraged!)

We should continue expanding this until it covers all support frameworks:

- [x] SvelteKit
- [x] NextJS
- [x] Vite/Svelte
- [x] Vite/React
- [x] Astro

### Related Task

- https://github.com/skeletonlabs/skeleton/issues/2714

### PR DESCRIPTION
**Pull request by phamduylong**
## Linked Issue

Closes #2653

## Description

Update installation instructions, add new instructions for Svelte + Vite, React + Vite and Astro projects

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
This looks awesome @phamduylong! Good catch on implementing the Tailwind directives for the Vite project, I almost always forget about it since it's automatic in Next.js/SvelteKit!

At a quick glance the only suggestion might be to set a defined order. You can do this by setting an `order` key in the frontmatter per page like so:

Screenshot 2024-12-12 at 4 42 54 PM

Order should be:

- Next.js
- SvelteKit
- Vite + React
- Vite + Svelte
- Astro

We're doing increments of `10` to leave a bit of padding in case pages need to be inserted in between later. Not additional effort should be needed beyond that, the NavGrid should adhere to the order set.

Don't be afraid to set Astro to like `1000` or something to ensure it's always last in the list.

I'll do a deeper review tomorrow and follow up with my additional modifications, but again thanks for the heads start on this one! You rock!

**Comment by phamduylong** [comment]
> This looks awesome @phamduylong! Good catch on implementing the Tailwind directives for the Vite project, I almost always forget about those since it's automatic in Next.js/SvelteKit!
> 
> At a quick glance the only suggestion might be to set a defined order per guide. You can do this by setting an `order` key in the frontmatter per page like so:
> 
> Screenshot 2024-12-12 at 4 42 54 PM
> 
> Order should be:
> 
> * Next.js
> * SvelteKit
> * Vite + React
> * Vite + Svelte
> * Astro
> 
> We're doing increments of `10` to leave a bit of padding in case pages need to be inserted in between later. No additional effort should be needed beyond that, the NavGrid should adhere to the order set. Don't be afraid to set Astro to like `1000` or something to ensure it's always last in the list.
> 
> I'll do a deeper review tomorrow and follow up with my additional modifications, but again thanks for the heads start on this one! You rock!

Sounds like a plan. The Astro guide likely need some work, I don't know enough to ensure that Skeleton would work over there. I'm happy to help to as always 😄

**Comment by endigo9740** [comment]
@phamduylong I've pushed a number of changes this afternoon, including:

1. Updating and improving the text and instruction per framework. Including CLI flags to auto-pick some options.
2. I've revised the Astro doc to include both the core AND component instructions.
3. I've added an additional "Other" guide, which is a generic guide as a catch-all for all other frameworks (Laravel, etc)

I'd welcome a quick review to ensure all is well. Check for typos, etc. I'll reach out to the team to have them do the same as well!

**Comment by endigo9740** [comment]
@phamduylong I've pushed one more round of updates. This includes:

- Updating the call-to-action buttons on the homepage to direct link the Installation page.
- Improving the content and instructions per each framework
- Added a blurb about support to the "Other" guide.

We'll test these instructions in the wild between the Release Candidate and full release sometime in January and plan to adjust as needed on the fly.

**Comment by phamduylong** [comment]
Sounds good to me! Thanks for the info Chris.

**Pull request merged**
