### PR TITLE
Check for slot content in `AppRail`

### PR DESCRIPTION
**Pull request by ibilux**
## Description

Check for `lead` and `trail` slots content in `AppRail` before inserting html code.

### CODE REVIEW

**Comment by Sarenor** [comment]
This doesn't look bad, but it should definitely include a change set.

**Comment by Mahmoud-zino** [comment]
The PR is targeting the master branch and the branch name doesn't follow Skeleton's style guide.
please reffer to https://www.skeleton.dev/docs/contributing

**Comment by endigo9740** [comment]
@ibilux if you need us to change the target branch we can, you should always target `dev` please. But a changeset will be required here. Our changelog is programmatic, generated from that. Make sure to read the PR message rather than replace it, it covers this and other requirements. See another PR if you need instruction for this.

**Comment by ibilux** [comment]
> The PR is targeting the master branch and the branch name doesn't follow Skeleton's style guide. please refer to https://www.skeleton.dev/docs/contributing

I didn't notice i was on the `master` branch, should I close it and make a new one in the `dev` branch.

**Comment by ibilux** [comment]
> @ibilux if you need us to change the target branch we can, you should always target `dev` please. But a changeset will be required here. Our changelog is programmatic, generated from that. Make sure to read the PR message rather than replace it, it covers this and other requirements. See another PR if you need instruction for this.

I think the `cBase` class should be updated too ?
```ts
const cBase = `grid grid-rows-[${[$$slots.lead?'auto':undefined,'1fr',$$slots.trail?'auto':undefined].filter(Boolean).join('_')}] overflow-y-auto`;
```

**Comment by endigo9740** [comment]
@ibilux I'd recommend reading through out style guide in the contributor section here:
https://www.skeleton.dev/docs/contributing/style-guide

We don't set dynamic values in the `cBase`. Create a reactive property to handle this.

**Comment by endigo9740** [comment]
@ibilux @Sarenor @Mahmoud-zino I was in process on switching the target branch and appending a changeset. However, after reviewing the change to the grid styling, I'm thinking this may not be a useful change. Having empty slots causes no harm, and would make adjusting the `grid-rows-x` styling VERY difficult to adjust per all possible configurations. The simplest solution is sometimes the best, so I think we're close this out and keep things as is.

**Pull request closed without merging**
