### PR TITLE
Docs Audit  - Tailwind Group 2 

### PR DESCRIPTION
**Pull request by DukeRupert**
Contributing to : 
- https://github.com/skeletonlabs/skeleton/issues/1049

## Checklist
- [x] Breadcrumbs
- [x] Buttons
- [x] Cards
- [x] Chips
- [x] Lists
- [x] Logo Clouds
- [x] Placeholders
- [x] Tables
- [x] Gradient Headings

### CODE REVIEW

**Comment by Hugos68** [comment]
On the button page, on smaller devices, the button size showcase dialog will have the outer most buttons clip on each side, not sure if this is desired.

**Comment by niktek** [comment]
@Hugos68 GO TO BED and CHARGE YOUR PHONE!
Can replicate that as well, I'll leave to @endigo9740 as to proper fix for it.
But looks like both two additional set of eyes have done a review now.

**Comment by endigo9740** [comment]
@niktek I was about to say the same about the phone lol

Per the layout, I had disabled the base button for that reason. But I think we can probably edit the text within the buttons to be:

sm | base | lg | xl

That *should* fit

**Comment by niktek** [comment]
New sizes work on mobile for me now

**Pull request merged**
