### PR TITLE
docs update on pagination  with dynamic size

### LINKED ISSUE #2211: Add information on how to have server side pagination with a dynamic size
### Link to the Page

https://www.skeleton.dev/components/paginators

### Describe the Issue (screenshots encouraged!)

I was having an issue while using the paginator, as it broke (numbers stopped updating correctly when changing page) when I added filters to my table (which in turn makes the size parameter dynamic, as it changes based on the select filters). 

I found no information in the documentation for this rather common pattern and I was able to come up with a solution of my own, with some help from other developers in the Discord server. However, I believe that, given how common this pattern is, it would make sense to add an example in the documents.

Here is my final solution:

```
paginationSettings = {
        page: Number($page.url.searchParams.get('pageNumber')),
        limit: 5,
        size: Number(data.Count), // This is the total count of the filtered data at any time and it is dynamic.
        amounts: []
    } satisfies PaginationSettings;

$: paginationSettings.size = Number(data.Count); // This ensures that the size property is updated whenever the load function runs (hence, when the data is filtered).
```

### PR DESCRIPTION
**Pull request by Riley1101**
## Add information on how to have server side pagination with a dynamic size

Closes #2211

## Description
Documentation on updating pagination size accordingly to the dynamic data source

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
Hey @Riley1101, per your PR - can you confirm you've tested this and ensure it works? My understanding and 
recommendation to users has always been to recreate the object if data within it changes.

Svelte details this in their tutorial:
https://learn.svelte.dev/tutorial/updating-arrays-and-objects

The general idea being if you just modify the values within the existing array/object, it wouldn't trigger trigger an updated render of that data. The Svelte specifically monitors only when there's a new instance of the array/object provided.

So I'd expect the correct way to update this would be more like:

```ts
let paginationSettings = {
    page: 0,
    limit: 5,
    size: source.length,
    amounts: [1, 2, 5, 10],
} satisfies PaginationSettings;

$: if (source.length)  paginationSettings = { ... paginationSettings, ... { size: source.length } };
```

I'd recommend testing this in a local project to verify which method works as expected here.

**Comment by endigo9740** [comment]
@Riley1101 quick update - I opened this up to testing from other contributors on our Discord. If you're a member take a look at the `#contributor` channel. Another contributor, Hugos, mentioned your method for updating this data should work. But this seems to run contrary to what the Svelte tutorial explains.

We're going to reach out in the Svelte discord for clarification on this. But currently it look like your solution would be more efficient. We just just wanna vet for any edge cases here.

**Comment by endigo9740** [comment]
@Riley1101 ok, per the Discord discussion we're good to move forward with your change here. Seems the Svelte doc is trying to point out you can't update a REFERENCE. But direct updates to the object values is fine for reactivity. That means your change here will be fine.

I will, however, make the suggesting that we append a small note to clarify this though. If it tripped us up, it'll likely trip up others.

Just append a small note to the description of this snippet that says something like: "make sure to update `paginatorSettings` directly, updating a reference will not trigger reactivity" or something along those lines. Maybe even provide an example mirroring the Svelte docs here to be explicitly clear.

Once that's in place I'm happy to merge. Thanks!

**Comment by Riley1101** [comment]
> @Riley1101 ok, per the Discord discussion we're good to move forward with your change here. Seems the Svelte doc is trying to point out you can't update a REFERENCE. But direct updates to the object values is fine for reactivity. That means your change here will be fine.
> 
> I will, however, make the suggesting that we append a small note to clarify this though. If it tripped us up, it'll likely trip up others.
> 
> Just append a small note to the description of this snippet that says something like: "make sure to update `paginatorSettings` directly, updating a reference will not trigger reactivity" or something along those lines. Maybe even provide an example mirroring the Svelte docs here to be explicitly clear.
> 
> Once that's in place I'm happy to merge. Thanks!

 I will try to add a bit more concise clarification to this Thanks @endigo9740

**Comment by endigo9740** [comment]
@Riley1101 thank you for the quick turn around. i went ahead and made a few modifications here as well, including making this it's own standalone section. That'll help us on the support end if we need to deep link to this topic.

Thanks for your contribution!

**Pull request merged**
