### PR TITLE
Add Optional Open/Close Functions

### LINKED ISSUE #1615: Allow for Passing Custom Functions to Open/Close event listeners on popups
### Describe the feature in detail (code, mocks, or screenshots encouraged)

The title pretty much describes the request.
I want to have make a `hover` popup that does not disappear when pressing shift. Currently it's not possible as the element has a `mouseleave` event listener telling the popup to be closed.

Example of what I want to achieve (the "window" is done by pressing Shift):

https://github.com/skeletonlabs/skeleton/assets/32039708/507c002e-d448-40bf-831c-7005b5c67211

Allowing to the user to pass their own open and close functions would allow for such additional functionality.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

There was once a conversation about attempting to create this sort of hover-to-window functionality, but it ended up going nowhere.

### PR DESCRIPTION
**Pull request by MrVauxs**
## Linked Issue

Closes #1615

## Description

A (definitely haphazard) implementation of the feature request. I have no idea of TypeScript.

## Changsets

khaki-olives-relax.md

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing/style-guide#feature-branches).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [ ] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure code linting is current - run `pnpm format`
- [ ] All test cases are passing - run `pnpm test` (errors with no test selected)
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
@MrVauxs we have a policy for contributions on Skeleton that non-trivial updates require prior discussion with maintainers. The idea being that we can prevent folks spending a lot of time on features we cannot accept.

Items number 4 found here:
https://www.skeleton.dev/docs/contributing/requirements#pull-requests

Had we had prior discussion I would have been able to point out this functionality already exists in the popup feature - via the `state` param. It's a callback function that you can provide and will trigger any time an `open` or `close` event occurs for a particular popup and the current state will be reported in the response.

Given the amount of effort you've devoted here, I'll give you a chance to explain the benefit of this over what's already in place. Though typically we would recommend extending an extending features than the providing redundant options.

**Comment by endigo9740** [comment]
@MrVauxs a bit more context as well if you check our roadmap:
https://github.com/skeletonlabs/skeleton/discussions/1367

We're in a transitionary phase where we've just migrated the project to a monorepo. As part of this we're looking to actually spin off the Popup feature to it's own standalone package. When we do this, we're going to likely rewrite or recreate the feature in a way that will more tightly integrate with Floating UI.

Floating UI will actually become a peer dependency for these package, which opens a lot of doors for us. A few brief examples of what that might include:

- Better type support through Floating UI's own provided types
- Simpler install process, given we can make this a peer dependency that NPM will auto-install
- No more need to pass the module import through a store to our action
- Plus we'll likely introduce new ways to use Floating UI - ex: a tap and hold context menu for mobile

Needless to say there's a lot of changes coming down the pipeline for this feature. But this is still a ways off. That said, we are field all input between now and then, so that's part of why I request your thoughts behind the request and change. Perhaps it's something we can consider for the future?

**Comment by MrVauxs** [comment]
Thanks.

The feature I am suggesting directly ties into the `open` and `close` event listeners so users can decide **when** the popups are closed and opened. This is not something that can be done with `state`, as you cannot modify whether the popup has been actually opened and closed with it. You are simply notified that it had been.

**Comment by endigo9740** [comment]
> The feature I am suggesting directly ties into the open and close event listeners so users can decide when the popups are closed and opened. This is not something that can be done with state, as you cannot modify whether the popup has been actually opened and closed with it. You are simply notified that it had been, but cannot influence it.

I follow, so it's programmatically triggering a open or close state, not listening for those. Hmm, that does seem useful.

I think this falls under a duplicate to:
- https://github.com/skeletonlabs/skeleton/issues/1484

This is an idea we're very much interested in exploring, but I'm leery to introduce any other additional major features to the popup in the near future given the proposed path  going forward. So let me think about this one for a bit. We'll keep it under consideration.

**Comment by MrVauxs** [comment]
> I think this falls under a duplicate to:
> 
> * [Investigate programatic popups #1484](https://github.com/skeletonlabs/skeleton/issues/1484)

I understand. It was on my radar but this is less about being able to programmatically create popups as much as what amounts to creating custom `events` basically.

But sure, I understand. Not sure if I should devote my time looking for a workaround or just focus on other things in the meantime...

**Comment by jwatts777** [comment]
@endigo9740 Funnily enough, this was exactly what I was looking for. I wanted custom control over the popup's state(open,close).
Nice work @MrVauxs. You just saved me 4+ hours. 
#1484 closing

**Comment by endigo9740** [comment]
@MrVauxs I've decided this is something we're interested in exploring, but won't be part of the current implementation. We'll wait until we migrate popups to a standalone tool to revisit. I've provided a note to reference this PR when we get to that point:
- https://github.com/skeletonlabs/skeleton/issues/1484#issuecomment-1587857706

For now I'm going to close this, but again, we'll use it as reference in the future. Thanks for the contribution and sorry if it takes a bit longer to get in place.

**Pull request closed without merging**
