### PR TITLE
Svelte group 1 docs review

### PR DESCRIPTION
**Pull request by niktek**
Contributing to:
- https://github.com/skeletonlabs/skeleton/issues/1049

Checklist
- [x] Clipboard
- [x] Filters
- [x] Focus Trap
- [x] Accordions
- [x] App Bar
- [x] App Rail
- [x] App Shell
- [x] Avatars
- [x] Conic Gradients
- [x] File Buttons
- [x] File Dropzone
- [x] Input Chips

### CODE REVIEW

**Comment by Sarenor** [comment]
You might want to decide on either space or no in Clipboard ;)
image

Focus Trap:
> Apply use:focusTrap then the action value to either true or false to enable or disable focus.
then _set_ the action value?

AppRail:
> This component implements [restProps](https://svelte.dev/docs#template-syntax-attributes-and-props). This passes all extra attributes to the component's AppRailTile element.
Should probably be AppRailTile elementS?
> Apply abitrary classes (in props)
Probably the whole repo needs a Find & Replace for abitrary to arbitrary
> Page State
Isn't that also handled with AppRailTile values & the selected store? I feel like we should mention that that's the default, recommended way

AppShell
> Apply abitrary classes (in props)
Probably the whole repo needs a Find & Replace for abitrary to arbitrary

FileDropzone
> Apply abitrary classes (in props)
Probably the whole repo needs a Find & Replace for abitrary to arbitrary

**Comment by Hugos68** [comment]
Under the clipboard input value section it states "To copy a form input value", shouldn't this apply to all input value's and therefor just be "To copy an input value"? No clue if I'm nitpicking here but something I noticed.

**Comment by endigo9740** [comment]
> Under the clipboard input value section it states "To copy a form input value", shouldn't this apply to all input value's and therefor just be "To copy an input value"? No clue if I'm nitpicking here but something I noticed.

The intention is it copies the input that you target. So perhaps insert that term?

"To copy the target input value...."

**Comment by endigo9740** [comment]
@niktek if all changes are current you've got my go ahead to merge!

**Comment by riziles** [comment]
@niktek , seems to be a minor issue on https://skeleton-docs-oi8f3pcbb-skeleton-labs.vercel.app/components/app-shell -> slots -> header:

image

**Comment by riziles** [comment]
... apologies if I'm looking at a stale page.

**Comment by riziles** [comment]
I think this is the line? 	

https://github.com/niktek/skeleton/blob/f4a0fa09a55f9f69d93f2e56d85bb79c1288a8c0/src/lib/components/AppShell/AppShell.svelte#L3

Sorry. Wait out of my depth right now.

**Comment by riziles** [comment]
moved here:

https://github.com/skeletonlabs/skeleton/issues/1049#issuecomment-1452915286

**Pull request merged**
