### PR TITLE
Feat/improve-search-ux

### LINKED ISSUE #567: Search results should be wrapped in an unordered list
### Link to the Page

_No response_

### Describe the Issue

We are going against our own advice with this; <nav> elements with links should have an unordered list. 

### Are you able to create a Pull Request with the fix?

Yes

### LINKED ISSUE #568: Search box should allow navigation to the first entry when you hit Enter
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Basically the exact same functionality as Tailwind's docs. It would be great to be able to type in "butt" to get to the button page, and then just hit Enter. Mouse = bad, keyboard = good! 

### What type of pull request would this be?

New Feature

### Any links to similar examples or other references we should review?

https://tailwindcss.com/

### LINKED ISSUE #569: Search box should have recently searched terms at the top
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

Similar to how Tailwind does it, it would be awesome to have the most recent searches at the top of the search results while the search box is empty, so that you can quickly refer back to things that you've recently needed to search for. This would be super easy to implement considering that we already have an implementation of local storage in place.

### What type of pull request would this be?

Enhancement

### Any links to similar examples or other references we should review?

https://tailwindcss.com/

### PR DESCRIPTION
**Pull request by ryceg**
## Before submitting the PR:
- [x] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/Brain-Bones/skeleton/discussions) before submission.
- [x] Did you update and run tests before submission using `npm run test`?
- [x] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributions)? If not, please amend the branch name using `branch -m new-branch-name`
- [x] Did you update documentation related to your new feature or changes?

## What does your PR address?

Adds a recently searched + favorited options to the search modal, as well as adds it in an unordered list, and lets you use the keyboard without needing the mouse to select entries.

### CODE REVIEW

**Comment by ryceg** [comment]
Submitting this as a draft because I'm not sure whether you'd like to add a lil animation to the save search / delete search

**Comment by niktek** [comment]
Hey @ryceg - I can't seem to get it to move focus into the list - before it was tab, tab, tab to go from search box to close button to list contents, but now it seems to cycle back to the search entry box.

There is also still the bug of being able to do multiple instantiations through cmd-k.

This is on Safari 16.1 in case it helps!

**Comment by endigo9740** [comment]
@ryceg @niktek The multiple search instantiation has been fixed on dev branch. It means this must be beyond.

@ryceg 
- Not sure I like the search being so empty on a first time use. Being able to browse the list manually was intentional.
- Using ESC for the close is great for desktop, less great on mobile (even though search isn't yet accessible there)

I haven't had a chance to implement search into the mobile drawer menu, but I do plan to FYI.

**Comment by endigo9740** [comment]
@ryceg I saw the improvements. What do you think about making the recent searches a section above the standard nav?

Like:

- Search bar
- Recent searches
- Standard list of links

Then limit the recent searches to say 3-5 so it doesn't get too long.

**Comment by endigo9740** [comment]
@ryceg I wanted to give this one a go but it looks like the things are so out of date it doesn't run with the current dependency updates. I'd need to nuke my node_modules and reinstall just for this PR to get it back in a working state.

I'd say let's either set a ETA for this within the next few days or we may have to close out and tackle this later. If we close it out I'd suggest we merge the proposed changes into a single ticket.

Thoughts?

**Comment by endigo9740** [comment]
@ryceg Unfortunately this one has gone on so long the merge conflicts are starting to pile up. I'm going to go ahead and close out the PR, but keep the tickets and reference this. We can aim to give this another go soon. Note that dev branch does have some minor UI improvements, though your items are not yet included.

**Pull request closed without merging**
