### PR TITLE
docs/tailwind-package-badge

### LINKED ISSUE #2292: Updated project readme to link to Tailwind NPM package
### Link to the Page

https://github.com/skeletonlabs/skeleton/blob/dev/README.md

### Describe the Issue (screenshots encouraged!)

image

We currently track the version of the core package using:

```
[![npm version](https://img.shields.io/npm/v/@skeletonlabs/skeleton?logo=npm&color=cb3837)](https://www.npmjs.com/package/@skeletonlabs/skeleton)
```

However, we should introduce an additional one to track the Tailwind plugin:
https://www.npmjs.com/package/@skeletonlabs/tw-plugin

We may need to alter the badges to include labels:
https://shields.io/

Suggestions:

* `[core]`
* `[tw-plugin]`

### PR DESCRIPTION
**Pull request by Mahmoud-zino**
## Linked Issue

Closes #2292

## Description

Adds an additional README badge to represent Tailwind plugin packages, in addition to the core.

Screenshot 2023-12-18 at 2 22 26 PM

## Changsets

Instructions: Changesets automate our changelog. If you modify files in `/packages`, run `pnpm changeset` in the root of the monorepo, follow the prompts, then commit the markdown file. Changes that add features should be `minor` while chores and bugfixes should be `patch`. Please prefix the changeset message with `feat:`, `bugfix:` or `chore:`.

## Checklist

Please read and apply all [contribution requirements](https://www.skeleton.dev/docs/contributing).

- [x] This PR targets the `dev` branch (NEVER `master`)
- [x] Documentation reflects all relevant changes
- [x] Branch is prefixed with: `docs/`, `feat/`, `chore/`, `bugfix/`
- [x] Ensure Svelte and Typescript linting is current - run `pnpm ci:check`
- [x] Ensure Prettier linting is current - run `pnpm format`
- [x] All test cases are passing - run `pnpm test`
- [x] Includes a changeset (if relevant; see above)

### CODE REVIEW

**Comment by endigo9740** [comment]
@Mahmoud-zino the problem here is we can't just duplicate the badges. They need to have a unique label, which may mean generating a badge through the steps or generator in the docs I linked. Otherwise folks won't be able to tell the two apart.

**Comment by Mahmoud-zino** [comment]
> @Mahmoud-zino the problem here is we can't just duplicate the badges. They need to have a unique label, which may mean generating a badge through the steps or generator in the docs I linked. Otherwise folks won't be able to tell the two apart.

They have different labels.
I didn't just duplicate them but also add the label queryParam.

**Comment by Mahmoud-zino** [comment]
@endigo9740 also I am really sorry I just noticed you assigned the issue to yourself before I created the PR, I will be more careful in the future 👍

**Comment by endigo9740** [comment]
@Mahmoud-zino no worries, I just wanted to make sure we met the criteria I had in mind. Sounds like you've nailed what I was after, and I'll aim to review either this weekend or next week. I'll have a lot more time starting on Monday, which will make this a much easier process.

**Pull request merged**
