### PR TITLE
Update +page.svelte

### PR DESCRIPTION
**Pull request by JustMrMendez**

### CODE REVIEW

**Comment by endigo9740** [comment]
Thanks @JustMrMendez

**Comment by endigo9740** [comment]
@JustMrMendez I noticed this too late, but please avoid sending PRs targeting Master. We merge into our dev branch -> then master on release. Pease be mindful of this in the future. Thanks.

**Comment by JustMrMendez** [comment]
Sorry, the view page source in de docs sent me here, and i just clicked edit and posted the change without much thought

**Comment by endigo9740** [comment]
All good, just a heads up! I've resolved the merges so everything is good now.

**Pull request merged**
