### PR TITLE
#1453 Clipboard now uses text/html when copying a node.

### PR DESCRIPTION
**Pull request by bertvh**
Also: an event is fired when copying is ready.

## Before submitting the PR:
- [x] Does your PR reference an issue? If not, please [chat to the team on Discord](https://discord.gg/EXqV7W8MtY) or [GitHub](https://github.com/skeletonlabs/skeleton/discussions) before submission.
- [x] Did you update and run tests before submission using `npm run test`?
- [ ] Does your branch follow our [naming convention](https://www.skeleton.dev/docs/contributing)? If not, please amend the branch name using `branch -m new-branch-name`
- [ ] Did you update documentation related to your new feature or changes?

## What does your PR address?

- When copying a html node, mime-type is set to text/html
- An event is fired when copy is done so you can e.g., easily show a toast as feedback to the user.

### Tips
- Tap "convert to draft" to indicate this is work in progress.
- Link to an issue using the verbiage [Fixes #XX](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- Linked issues will auto-close when the PR is merged.

### CODE REVIEW

**Comment by endigo9740** [comment]
Thank you @bertvh, we're aiming for a new release to drop tomorrow so I'll be in the midst of prepping for that. Then I'll aim to circle back to this PR later this week.

**Comment by endigo9740** [comment]
Hey @bertvh, finally had a chance to review this. The concept seems sound, but unfortunately one of the examples on our documentation is not working for me - specifically the "Copying HTML Contents" demo. When I tap copy I receive no errors, but when I try to paste the content it's blank.

Here's my steps to replicate:

- Testing on Chrome for macOS. Should be the latest version of both.
- Copy anything notable on the page to have as my current clipboard value
- Paste this into an empty document in VS Code -> this works
- Return to the HTML content demo and tap "Copy"
- Paste this into an empty document in VS Code -> nothing, no content

What's notable is it's not pasting the previous clipboard value, it's like it's trying to to paste some kind of value but nothing is present.

Any ideas here?

**Comment by bertvh** [comment]
@endigo9740 .. pushed a fix. The content is not put on the clipboard as both plain and html so that the app in which you paste can choose the best option.

We get a nice extra here: 'pasting without formatting'. Below: first is a normal paste, second without formatting.

image

**Comment by endigo9740** [comment]
Seems like a good fix @bertvh, thanks for the contribution I'll go ahead and merge and this should be part of the next release.

Quick side note - in the future, be sure to bump your draft PRs up to "ready for review" state when you're ready for me to audit. Just helps ensure I don't miss it! Thanks!

**Pull request merged**
